// Generated by psc-bundle 0.7.6.1
var PS = { };
(function(exports) {
  /* global exports */
  "use strict";

  // module Control.Monad.Eff

  exports.returnE = function (a) {
    return function () {
      return a;
    };
  };

  exports.bindE = function (a) {
    return function (f) {
      return function () {
        return f(a())();
      };
    };
  };
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  //- Eq -------------------------------------------------------------------------

  exports.refEq = function (r1) {
    return function (r2) {
      return r1 === r2;
    };
  };
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Prelude"];
  var Functor = function (map) {
      this.map = map;
  };
  var Apply = function (__superclass_Prelude$dotFunctor_0, apply) {
      this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
      this.apply = apply;
  };
  var Applicative = function (__superclass_Prelude$dotApply_0, pure) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.pure = pure;
  };
  var Bind = function (__superclass_Prelude$dotApply_0, bind) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.bind = bind;
  };
  var Monad = function (__superclass_Prelude$dotApplicative_0, __superclass_Prelude$dotBind_1) {
      this["__superclass_Prelude.Applicative_0"] = __superclass_Prelude$dotApplicative_0;
      this["__superclass_Prelude.Bind_1"] = __superclass_Prelude$dotBind_1;
  };
  var Eq = function (eq) {
      this.eq = eq;
  };                  
  var pure = function (dict) {
      return dict.pure;
  };
  var $$return = function (__dict_Applicative_2) {
      return pure(__dict_Applicative_2);
  };
  var map = function (dict) {
      return dict.map;
  }; 
  var eqString = new Eq($foreign.refEq);
  var eq = function (dict) {
      return dict.eq;
  };
  var bind = function (dict) {
      return dict.bind;
  };
  var $greater$greater$eq = function (__dict_Bind_24) {
      return bind(__dict_Bind_24);
  }; 
  var apply = function (dict) {
      return dict.apply;
  };
  var $less$times$greater = function (__dict_Apply_25) {
      return apply(__dict_Apply_25);
  };
  var liftA1 = function (__dict_Applicative_26) {
      return function (f) {
          return function (a) {
              return $less$times$greater(__dict_Applicative_26["__superclass_Prelude.Apply_0"]())(pure(__dict_Applicative_26)(f))(a);
          };
      };
  };
  var ap = function (__dict_Monad_30) {
      return function (f) {
          return function (a) {
              return bind(__dict_Monad_30["__superclass_Prelude.Bind_1"]())(f)(function (_2) {
                  return bind(__dict_Monad_30["__superclass_Prelude.Bind_1"]())(a)(function (_1) {
                      return $$return(__dict_Monad_30["__superclass_Prelude.Applicative_0"]())(_2(_1));
                  });
              });
          };
      };
  };
  exports["Eq"] = Eq;
  exports["Monad"] = Monad;
  exports["Bind"] = Bind;
  exports["Applicative"] = Applicative;
  exports["Apply"] = Apply;
  exports["Functor"] = Functor;
  exports["eq"] = eq;
  exports["ap"] = ap;
  exports[">>="] = $greater$greater$eq;
  exports["bind"] = bind;
  exports["liftA1"] = liftA1;
  exports["pure"] = pure;
  exports["apply"] = apply;
  exports["map"] = map;
  exports["eqString"] = eqString;;
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Control.Monad.Eff"];
  var Prelude = PS["Prelude"];     
  var monadEff = new Prelude.Monad(function () {
      return applicativeEff;
  }, function () {
      return bindEff;
  });
  var bindEff = new Prelude.Bind(function () {
      return applyEff;
  }, $foreign.bindE);
  var applyEff = new Prelude.Apply(function () {
      return functorEff;
  }, Prelude.ap(monadEff));
  var applicativeEff = new Prelude.Applicative(function () {
      return applyEff;
  }, $foreign.returnE);
  var functorEff = new Prelude.Functor(Prelude.liftA1(applicativeEff));
  exports["functorEff"] = functorEff;
  exports["applyEff"] = applyEff;
  exports["applicativeEff"] = applicativeEff;
  exports["bindEff"] = bindEff;
  exports["monadEff"] = monadEff;;
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  exports.unsafeQuerySelector = function (selector) {
    return function (src) {
      return function () {
        return src.querySelector(selector);
      };
    };
  };

  exports.unsafeSetAttribute = function (name) {
    return function (value) {
      return function (src) {
        return function () {
          src.setAttribute(name, value);
          return {};
        };
      };
    };
  };

  exports.unsafeRemoveAttribute = function (name) {
    return function (src) {
      return function () {
        src.removeAttribute(name);
        return {};
      };
    };
  };

  exports.unsafeTextContent = function (src) {
    return function () {
      return src.textContent;
    };
  };

  exports.unsafeSetTextContent = function (value) {
    return function (src) {
      return function () {
        src.textContent = value;
        return {};
      };
    };
  };

  exports.unsafeValue = function (src) {
    return function () {
      return src.value;
    };
  };
 
})(PS["Data.DOM.Simple.Unsafe.Element"] = PS["Data.DOM.Simple.Unsafe.Element"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Unsafe.Element"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var DOM_Node_Types = PS["DOM.Node.Types"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Unsafe_Utils = PS["Data.DOM.Simple.Unsafe.Utils"];
  exports["unsafeValue"] = $foreign.unsafeValue;
  exports["unsafeSetTextContent"] = $foreign.unsafeSetTextContent;
  exports["unsafeTextContent"] = $foreign.unsafeTextContent;
  exports["unsafeRemoveAttribute"] = $foreign.unsafeRemoveAttribute;
  exports["unsafeSetAttribute"] = $foreign.unsafeSetAttribute;
  exports["unsafeQuerySelector"] = $foreign.unsafeQuerySelector;;
 
})(PS["Data.DOM.Simple.Unsafe.Element"] = PS["Data.DOM.Simple.Unsafe.Element"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.DOM.Simple.Unsafe.Events

  exports.unsafeAddEventListener = function (targ) {
    return function (cb) {
      return function (src) {
        return function () {
          src.addEventListener(targ, function (evt) {
            cb(evt)();
          });
        };
      };
    };
  };

  exports.unsafeEventTarget = function (event) {
    return function () {
      return event.target;
    };
  };
 
})(PS["Data.DOM.Simple.Unsafe.Events"] = PS["Data.DOM.Simple.Unsafe.Events"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Unsafe.Events"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  exports["unsafeEventTarget"] = $foreign.unsafeEventTarget;
  exports["unsafeAddEventListener"] = $foreign.unsafeAddEventListener;;
 
})(PS["Data.DOM.Simple.Unsafe.Events"] = PS["Data.DOM.Simple.Unsafe.Events"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.DOM.Simple.Unsafe.Window

  exports.unsafeDocument = function (win) {
    return function () {
      return win.document;
    };
  };
 
})(PS["Data.DOM.Simple.Unsafe.Window"] = PS["Data.DOM.Simple.Unsafe.Window"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Unsafe.Window"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Document = PS["Data.DOM.Simple.Document"];
  exports["unsafeDocument"] = $foreign.unsafeDocument;;
 
})(PS["Data.DOM.Simple.Unsafe.Window"] = PS["Data.DOM.Simple.Unsafe.Window"] || {});
(function(exports) {
  /* global exports, window */
  "use strict";

  // module Data.DOM.Simple.Window

  exports.globalWindow = window;
 
})(PS["Data.DOM.Simple.Window"] = PS["Data.DOM.Simple.Window"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Window"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Unsafe_Window = PS["Data.DOM.Simple.Unsafe.Window"];
  var Data_DOM_Simple_Document = PS["Data.DOM.Simple.Document"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Array = PS["Data.Array"];
  var Data_String = PS["Data.String"];
  exports["globalWindow"] = $foreign.globalWindow;;
 
})(PS["Data.DOM.Simple.Window"] = PS["Data.DOM.Simple.Window"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Unsafe_Element = PS["Data.DOM.Simple.Unsafe.Element"];
  var Data_DOM_Simple_Unsafe_Events = PS["Data.DOM.Simple.Unsafe.Events"];
  var Data_DOM_Simple_Unsafe_Window = PS["Data.DOM.Simple.Unsafe.Window"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Window = PS["Data.DOM.Simple.Window"];
  var DOM = PS["DOM"];
  var Prelude = PS["Prelude"];     
  var querySelector = function (query) {
      return Prelude[">>="](Control_Monad_Eff.bindEff)(Data_DOM_Simple_Unsafe_Window.unsafeDocument(Data_DOM_Simple_Window.globalWindow))(Data_DOM_Simple_Unsafe_Element.unsafeQuerySelector(query));
  };
  var disableIfEmpty = function (button) {
      return function (content) {
          var _2 = Prelude.eq(Prelude.eqString)(content)("");
          if (_2) {
              return function __do() {
                  Data_DOM_Simple_Unsafe_Element.unsafeSetTextContent("Aye! Gimme a name!")(button)();
                  return Data_DOM_Simple_Unsafe_Element.unsafeRemoveAttribute("disabled")(button)();
              };
          };
          if (!_2) {
              return function __do() {
                  Data_DOM_Simple_Unsafe_Element.unsafeSetTextContent("Arrr! Write yer name!")(button)();
                  return Data_DOM_Simple_Unsafe_Element.unsafeSetAttribute("disabled")("true")(button)();
              };
          };
          throw new Error("Failed pattern match at Main line 56, column 1 - line 57, column 1: " + [ _2.constructor.name ]);
      };
  };
  var setBadgeName = function (name) {
      return function __do() {
          var _1 = querySelector("#badgeName")();
          var _0 = querySelector("#generateButton")();
          Data_DOM_Simple_Unsafe_Element.unsafeSetTextContent(name)(_1)();
          return Prelude[">>="](Control_Monad_Eff.bindEff)(Data_DOM_Simple_Unsafe_Element.unsafeTextContent(_1))(disableIfEmpty(_0))();
      };
  };
  var generateBadge = function (event) {
      return setBadgeName("Anne Bonney");
  };
  var updateBadge = function (event) {
      return Prelude[">>="](Control_Monad_Eff.bindEff)(Prelude[">>="](Control_Monad_Eff.bindEff)(Data_DOM_Simple_Unsafe_Events.unsafeEventTarget(event))(Data_DOM_Simple_Unsafe_Element.unsafeValue))(setBadgeName);
  };
  var main = function __do() {
      Prelude[">>="](Control_Monad_Eff.bindEff)(querySelector("#inputName"))(Data_DOM_Simple_Unsafe_Events.unsafeAddEventListener("input")(updateBadge))();
      return Prelude[">>="](Control_Monad_Eff.bindEff)(querySelector("#generateButton"))(Data_DOM_Simple_Unsafe_Events.unsafeAddEventListener("click")(generateBadge))();
  };
  exports["disableIfEmpty"] = disableIfEmpty;
  exports["updateBadge"] = updateBadge;
  exports["setBadgeName"] = setBadgeName;
  exports["querySelector"] = querySelector;
  exports["main"] = main;
  exports["generateBadge"] = generateBadge;;
 
})(PS["Main"] = PS["Main"] || {});

PS["Main"].main();
